#!/bin/bash
#
# check if a medium size command line does not break the shell

command="                                       /bin/ls                                                                                                                                                                                                                                                                                                                                                                                                                                                     "
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
$RM -f $tmp_file
$RM -f $OUTPUTFILE
$RM -f $ERROROUTPUTFILE

# create a pseudo random file
$TOUCH $tmp_file
$TOUCH $OUTPUTFILE

# send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &
$ECHO "$command" | $SHELLSYS > $tmp_file 2> $ERROROUTPUTFILE &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
if $CMP --silent -- "$OUTPUTFILE" "$tmp_file"; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
$RM -f $tmp_file
$RM -f $OUTPUTFILE
$RM -f $ERROROUTPUTFILE
