#!/bin/bash
#
# run printenv and compare it to env

tmp_file="checker_tmp_file_$RANDOM"
command="env"
command_sys="printenv"

# clean up
stop_shell
$RM -f $tmp_file
$RM -f $OUTPUTFILE
$RM -f $ERROROUTPUTFILE

# create a pseudo random file
$TOUCH $tmp_file
$TOUCH $OUTPUTFILE
$TOUCH $ERROROUTPUTFILE

# send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &
$ECHO "$command_sys" | $SHELLSYS > $tmp_file 2> $ERROROUTPUTFILE &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
if $CMP --silent -- "$OUTPUTFILE" "$tmp_file"; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
$RM -f $tmp_filepath
$RM -f $OUTPUTFILE
$RM -f $ERROROUTPUTFILE
