#!/bin/bash
#
# check if the getline function was used by using ltrace

command="/bin/ls
/bin/ls
/bin/ls"

# clean up
stop_shell
$RM -f $OUTSS
$RM -f $OUTERRSS
$RM -f $OUTLTRACE

# create a pseudo random file
$TOUCH $OUTSS
$TOUCH $OUTERRSS
$TOUCH $OUTLTRACE

# give each file read write permission
$CHMOD u+rw $OUTSS
$CHMOD u+rw $OUTERRSS
$CHMOD u+rw $OUTLTRACE

# send commands
$ECHO "$command" | $LTRACE -bc -o $OUTLTRACE $SHELL > $OUTSS 2> $OUTERRSS &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`$CAT $OUTLTRACE | $GREP getline | wc -l`
if [ $nmatch -eq 1 ]; then
    print_ko
else
    print_ok
fi

# clean up
stop_shell
$RM -f $OUTSS
$RM -f $OUTERRSS
$RM -f $OUTLTRACE
