#!/bin/bash
#
# Empty the PATH and check if /bin/ls still works

command="/bin/ls"

# clean up
stop_shell
$RM -f $OUTSYS
$RM -f $OUTSS
$RM -f $OUTERRSYS
$RM -f $OUTERRSS

# create a pseudo random file
$TOUCH $OUTSYS
$TOUCH $OUTSS
$TOUCH $OUTERRSYS
$TOUCH $OUTERRSS

# give each file read write permission
$CHMOD u+rw $OUTSYS
$CHMOD u+rw $OUTSS
$CHMOD u+rw $OUTERRSYS
$CHMOD u+rw $OUTERRSS

# empty PATH
OLDPATH="$PATH"
PATH=""

# run command
$ECHO "$command" | $SHELL > $OUTSS 2> $OUTERRSS &
$ECHO "$command" | $SHELLSYS > $OUTSYS 2> $OUTERRSYS &

# put PATH back
PATH="$OLDPATH"

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
if $CMP --silent -- "$OUTSS" "$OUTSYS"; then
           print_ok
else
           print_ko
fi

# clean up
stop_shell
$RM -f $OUTSYS
$RM -f $OUTSS
$RM -f $OUTERRSYS
$RM -f $OUTERRSS
