#!/bin/bash
#
# Empty the PATH and check if /bin/ls still works

command="/bin/ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file
rm -f $OUTPUTFILE
rm -f $ERROROUTPUTFILE

# create a pseudo random file
touch $tmp_file
touch $OUTPUTFILE
touch $ERROROUTPUTFILE

# empty PATH
OLDPATH="$PATH"
PATH=""

# send commands
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &
$ECHO "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# put PATH back
PATH="$OLDPATH"

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
if cmp --silent -- "$OUTPUTFILE" "$tmp_file"; then
    print_ok
else
    print_ko
fi

# clean up
stop_shell
$RM -f $tmp_file
$RM -f $OUTPUTFILE
$RM -f $ERROROUTPUTFILE
